### ISSUE TITLE
added tilt functionality

### ISSUE THREAD

**Issue by davidiola** [sgarcez/gomonome#1]
Hi i've added support for the tilt sensor. not sure how to make a pull request but i've attached the code from the files i changed (examples/simple/main.go, monome/grid.go).  Had to change them to .txt files for github to let me upload. if you need to reach me contact me at my email: davidaldeniola@gmail.com.  I'd love to continue to contribute to the project, I think I'm going to make a golang snake game utilizing the tilt sensor on my grayscale 64 next.

[main.txt](https://github.com/sgarcez/gomonome/files/2583504/main.txt)
[grid.txt](https://github.com/sgarcez/gomonome/files/2583505/grid.txt)

**Comment by sgarcez** [comment]
Thanks @davidiola!

If you'd like to look into submitting a PR please take at look at the instructions [here](https://help.github.com/articles/creating-a-pull-request/). You simply need to fork the repo, make a branch on your fork and then open a PR back to this repo. That way your contribution will be registered as it should.

In terms of contributing, the main outstanding task is to finish implementing the remaining message types. Then I intend to review the API before tagging a v1 release.

I've also made a snake game using a grid128 and an arc2: [https://github.com/sgarcez/python-monome-snake](https://github.com/sgarcez/python-monome-snake)
